// File generated by hand from the Firebase console app configs
// (project: smart-medicine-cabinet-iot), following the same shape the
// FlutterFire CLI (`flutterfire configure`) generates.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Usage:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'register an iOS app in the Firebase console and add its config '
          'here (or run the FlutterFire CLI) to enable Firebase on iOS.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'register a macOS app in the Firebase console and add its config '
          'here (or run the FlutterFire CLI) to enable Firebase on macOS.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'this app has not been registered with a Windows Firebase config.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'this app has not been registered with a Linux Firebase config.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Registered in the Firebase console as the "smart-medicine-cabinet-middleware" web app.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWgSwkU221Unb7yLEt7Rk8NxW99oQnz5A',
    appId: '1:725518502362:web:fa9f42444d7e346604d8e3',
    messagingSenderId: '725518502362',
    projectId: 'smart-medicine-cabinet-iot',
    authDomain: 'smart-medicine-cabinet-iot.firebaseapp.com',
    storageBucket: 'smart-medicine-cabinet-iot.firebasestorage.app',
  );

  // Registered in the Firebase console as the "iot_app" Android app
  // (my.edu.tarumt.iot_app) - matches android/app/google-services.json.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzPIhm4iknxNbSizKhQ3layh9ogt2GcXU',
    appId: '1:725518502362:android:d3743670cac8c17d04d8e3',
    messagingSenderId: '725518502362',
    projectId: 'smart-medicine-cabinet-iot',
    storageBucket: 'smart-medicine-cabinet-iot.firebasestorage.app',
  );
}
